# Generated by Django 4.2.6 on 2023-10-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_content',
            new_name='content',
        ),
    ]
